#!/usr/bin/env bash

set -euo pipefail
umask 077

if (( $# != 0 )); then
  printf 'This script reads MELANGE_PERSONAL_KEY from the environment or a hidden prompt; arguments are not accepted.\n' >&2
  exit 2
fi

if [[ -n "${MELANGE_PERSONAL_KEY:-}" ]]; then
  personal_key="$MELANGE_PERSONAL_KEY"
else
  printf 'Create a Melange Personal Access Token at https://melange.zetic.ai/settings?tab=pat\n' >&2
  read -r -s -p 'Melange personal key: ' personal_key
  printf '\n' >&2
fi

if [[ -z "$personal_key" ]]; then
  printf 'A non-empty Melange personal key is required.\n' >&2
  exit 1
fi

if [[ "$personal_key" == *$'\n'* || "$personal_key" == *$'\r'* ]]; then
  printf 'The Melange personal key must be a single line.\n' >&2
  exit 1
fi

escape_properties_value() {
  local value="$1"
  value="${value//\\/\\\\}"
  printf '%s' "$value"
}

escape_xcconfig_value() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

android_file="android/.melange.local.properties"
ios_file="ios/Config/Melange.local.xcconfig"
mkdir -p "$(dirname "$android_file")" "$(dirname "$ios_file")"

android_temp="$(mktemp "${android_file}.tmp.XXXXXX")"
ios_temp="$(mktemp "${ios_file}.tmp.XXXXXX")"
trap 'rm -f "$android_temp" "$ios_temp"' EXIT

chmod 600 "$android_temp" "$ios_temp"
printf '# Generated by setup.sh. Do not commit.\nMELANGE_PERSONAL_KEY=%s\n' "$(escape_properties_value "$personal_key")" > "$android_temp"
printf '// Generated by setup.sh. Do not commit.\nMELANGE_PERSONAL_KEY = %s\n' "$(escape_xcconfig_value "$personal_key")" > "$ios_temp"

mv -f "$android_temp" "$android_file"
mv -f "$ios_temp" "$ios_file"
trap - EXIT

printf 'Melange personal key configured for Android and iOS local development.\n'
